<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>IGLESIA_FDAE</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\logo.png" />
    <None Remove="biblia_himnario\biblia.json" />
    <None Remove="biblia_himnario\himnos.json" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="biblia_himnario\biblia.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="biblia_himnario\himnos.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\logo.png" />
  </ItemGroup>

</Project>
